version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "morenicano"
    groups:
      dependency-management:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
      type-definitions:
        patterns:
          - "@types/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "morenicano"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "morenicano"
