name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "a5b3081992c9b5b608c5a39fea5a18d0"
          workingDirectory: "apps/api"
          wranglerVersion: "4.76.0"
          command: deploy --minify --name cash-api
          secrets: |
            DISCORD_TOKEN
            DISCORD_PUBLIC_KEY
            JWT_SECRET
            METHOD_API_KEY
            ARCADIA_API_KEY
            PLAID_CLIENT_ID
            PLAID_SECRET
            PRIVACY_API_KEY
            AKOYA_CLIENT_ID
            AKOYA_SECRET
            ARGYLE_API_KEY
            ARGYLE_SECRET
            COLUMN_TAX_API_KEY
            ARRAY_API_KEY
            RESEND_API_KEY
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          METHOD_API_KEY: ${{ secrets.METHOD_API_KEY }}
          ARCADIA_API_KEY: ${{ secrets.ARCADIA_API_KEY }}
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PRIVACY_API_KEY: ${{ secrets.PRIVACY_API_KEY }}
          AKOYA_CLIENT_ID: ${{ secrets.AKOYA_CLIENT_ID }}
          AKOYA_SECRET: ${{ secrets.AKOYA_SECRET }}
          ARGYLE_API_KEY: ${{ secrets.ARGYLE_API_KEY }}
          ARGYLE_SECRET: ${{ secrets.ARGYLE_SECRET }}
          COLUMN_TAX_API_KEY: ${{ secrets.COLUMN_TAX_API_KEY }}
          ARRAY_API_KEY: ${{ secrets.ARRAY_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
