name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 'a5b3081992c9b5b608c5a39fea5a18d0'
          workingDirectory: 'apps/api'
          command: deploy --minify --config wrangler.jsonc
          secrets: |
            DISCORD_TOKEN
            DISCORD_PUBLIC_KEY
            JWT_SECRET
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
